### ISSUE TITLE
Add Mood-Tracking ShortCode

### ISSUE THREAD

**Issue by mikepsinn** [Abolitionist-Project/QuantiModo-WordPress-Plugin#2]
We want to be able to embed those faces in any page or post using shortcode: [qm_track_mood] 

Demo: https://chrome.google.com/webstore/detail/moodimodo-beta/lncgjbhijecjdbdgeigfodmiimpmlelg?hl=en-US

Here's the code for this Chrome extension that can be reused in the WP plugin: https://github.com/QuantiModo/QuantiModo-WordPress-Plugin/tree/master/reference/symptom-rating-page

![moodimodo chrome screenshot](https://cloud.githubusercontent.com/assets/2808553/8116915/6fe35728-104a-11e5-9c13-050d370a1332.jpg)

**Comment by megarocks** [comment]
[qmwp_mood_tracker]
