### ISSUE TITLE
QuantiModo appears twice in the WP settings menu

### ISSUE THREAD

**Issue by mikepsinn** [Abolitionist-Project/QuantiModo-WordPress-Plugin#21]

**Comment by megarocks** [comment]
Should be fixed

**Comment by mikepsinn** [comment]
I'm still seeing it twice.

**Comment by megarocks** [comment]
Checked at app.qm and quantipress.qm. Looks good.
<img width="282" alt="screen shot 2015-09-17 at 1 34 10 pm" src="https://cloud.githubusercontent.com/assets/2786005/9931059/dabdc6f8-5d40-11e5-87b4-93074a7d5a48.png">

**Comment by mikepsinn** [comment]
No, go to the WP "Settings" menu. Not "Plugins".
