### ISSUE TITLE
3rd party sites. Error on page with qmwp shortcode when user in not logged in.

### ISSUE THREAD

**Issue by megarocks** [Abolitionist-Project/QuantiModo-WordPress-Plugin#30]
<img width="795" alt="screen shot 2015-09-09 at 2 47 21 pm" src="https://cloud.githubusercontent.com/assets/2786005/9760901/cf7faaee-5701-11e5-9bc9-fef4203e592d.png">

**Comment by mikepsinn** [comment]
Yeah

Vitaly Kyktov [06:55] 
I’ve logged in to my local WP and now getting a list of other issues...

Mike Sinn [06:56] 
I guess we shouldn't be using login with AJAX
Vitaly Kyktov 
[06:56]  
Uploaded an image: Screen Shot 2015-09-09 at 2.51.09 PM.png 
Add Comment

Mike Sinn [06:56] 
Can you remove those references from the plugin?

Vitaly Kyktov [06:56] 
Ok. I’ll take a look

Mike Sinn [06:56] 
Also, we're using `/plugins/quantimodo-wordpress-plugin` when we get it from Composer. (edited)

Mike Sinn [06:57]
I'm not sure if that matters

Mike Sinn [06:57]
but you might want to make it that to keep it consistent.
