### ISSUE TITLE
Import Data Shortcode

### ISSUE THREAD

**Issue by mikepsinn** [Abolitionist-Project/QuantiModo-WordPress-Plugin#6]
Shortcode - [qm_connectors]

To see how it works:
- Create an account at https://quantimo.do
- Connect the Weather connector at https://quantimo.do/connect (using "62034" as your zip code if you're not on Earth and you don't have a location to enter.)

![quantimodo manage connected accounts - google chrome 10152014 63216 pm](https://cloud.githubusercontent.com/assets/2808553/8172734/39b6f640-1389-11e5-9d1c-332d4e5a7c54.jpg)

The code for this page is located here:
https://github.com/QuantiModo/QuantiModo-WordPress-Plugin/tree/develop/reference/connect-page

**Comment by megarocks** [comment]
[qmwp_connectors]
